name: Make

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: sudo apt install build-essential

    - name: Build
      shell: bash
      run: make TARGET_RPI=1 -j4
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Mario
        path: build/us_pc/sm64.us.f3dex2e.arm
